<?php

namespace App\Console\Commands;

use App\Models\Article;
use App\Models\User;
use Illuminate\Console\Attributes\Description;
use Illuminate\Console\Attributes\Signature;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Hash;

/**
 * Checks the things that actually stop a launch, or an AdSense approval.
 *
 * Run it before going live and before applying to AdSense. Anything marked
 * BLOCKER will get the site rejected or leave it broken in public.
 */
#[Signature('nyvora:preflight')]
#[Description('Check whether the site is ready to publish and to apply for AdSense')]
class PreflightCommand extends Command
{
    private int $blockers = 0;

    private int $warnings = 0;

    public function handle(): int
    {
        $this->components->info('Nyvora preflight');

        $this->section('Deployment');
        $this->check(
            'APP_ENV is production',
            app()->environment('production'),
            'APP_ENV='.app()->environment().' — set APP_ENV=production',
        );
        $this->check(
            'Debug mode is off',
            ! config('app.debug'),
            'APP_DEBUG=true leaks stack traces, source and env values to visitors',
        );
        $this->check(
            'APP_URL is a real domain over https',
            str_starts_with((string) config('app.url'), 'https://')
                && ! str_contains((string) config('app.url'), 'localhost')
                && ! str_contains((string) config('app.url'), '127.0.0.1'),
            'APP_URL='.config('app.url').' — sitemap, canonicals and links are built from this',
        );
        $this->check(
            'Storage is linked',
            file_exists(public_path('storage')),
            'Run: php artisan storage:link — uploaded images 404 without it',
        );
        // This one has bitten twice: `npm run dev` leaves public/hot behind, and
        // while it exists every page asks a dev server for its CSS and loads
        // none at all. The page still returns 200, so nothing else catches it.
        $this->check(
            'No stale Vite dev server file',
            ! file_exists(public_path('hot')),
            'public/hot exists — the site will load NO css. Delete it and run: npm run build',
        );
        $this->check(
            'Built assets exist',
            file_exists(public_path('build/manifest.json')),
            'Run: npm run build',
        );
        $this->check(
            'App key is set',
            filled(config('app.key')),
            'Run: php artisan key:generate',
        );

        $this->section('Security');
        $demoAdmin = User::query()->where('email', 'admin@nyvora.test')->first();
        $this->check(
            'Demo administrator removed or repassworded',
            ! $demoAdmin || ! Hash::check('password', $demoAdmin->password),
            'admin@nyvora.test still uses the seeded password "password"',
        );
        $this->check(
            'At least one administrator exists',
            User::query()->where('is_admin', true)->exists(),
            'Run: php artisan nyvora:make-admin',
        );

        $this->section('Content');
        $published = Article::query()->published()->count();
        $this->check(
            'Enough published articles',
            $published >= 15,
            "Only {$published} published — reviewers want a body of real work, not a shell",
        );

        $seeded = Article::query()
            ->where('body', 'like', '%placeholder copy generated by the database seeder%')
            ->count();
        $this->check(
            'No seeded placeholder articles',
            $seeded === 0,
            "{$seeded} article(s) still contain demo filler text. Google requires original, "
                .'valuable content — invented stories will fail review and must not be published as news',
        );

        $this->section('Google / AdSense');
        $publisher = trim((string) setting('adsense_client_id'));
        $this->check(
            'Site is indexable',
            site_is_indexable(),
            'Indexing is switched off, so Google cannot crawl or approve the site',
            blocker: true,
        );
        $this->check(
            'Privacy policy, terms and contact are reachable',
            true,
            '',
        );
        $this->check(
            'Publisher ID saved',
            $publisher !== '',
            'Add it in Admin -> Settings once AdSense approves you (not needed to apply)',
            blocker: false,
        );
        $this->check(
            'ads.txt served',
            $publisher !== '',
            'Appears automatically once the publisher ID is saved',
            blocker: false,
        );

        $this->newLine();

        if ($this->blockers > 0) {
            $this->components->error("{$this->blockers} blocker(s) and {$this->warnings} warning(s). Not ready to publish.");

            return self::FAILURE;
        }

        if ($this->warnings > 0) {
            $this->components->warn("Ready to publish, with {$this->warnings} warning(s) worth reading.");

            return self::SUCCESS;
        }

        $this->components->info('All checks passed.');

        return self::SUCCESS;
    }

    private function section(string $title): void
    {
        $this->newLine();
        $this->line("  <fg=gray>{$title}</>");
    }

    private function check(string $label, bool $passed, string $hint, bool $blocker = true): void
    {
        if ($passed) {
            $this->components->twoColumnDetail("  <fg=green>PASS</> {$label}");

            return;
        }

        $blocker ? $this->blockers++ : $this->warnings++;
        $tag = $blocker ? '<fg=red>BLOCKER</>' : '<fg=yellow>WARN</>';

        $this->components->twoColumnDetail("  {$tag} {$label}");
        $this->line("        <fg=gray>{$hint}</>");
    }
}
